---
title: "Homework 4"
author: "Shawn Rich"
date: "September 29, 2015"
output: html_document
---

## Question 1  
Load the data set mtcars in the datasets R package. Assume that the data set mtcars is a random sample. Compute the mean MPG, $\bar{x}$, of this sample.  
You want to test whether the true MPG is $\mu_0$ or smaller using a one sided 5% level test. ($H_0:\mu=\mu_0$ versus $H_a:\mu<\mu_0$). Using that data set and a Z test:  

1. Based on the mean MPG of the sample $\bar{x}, and by using a Z test: what is the smallest value of $\mu_0$ that you would reject for (to two decimal places)?


## Question 2  
Consider again the mtcars dataset. Use a two group t-test to test the hypothesis that the 4 and 6 cyl cars have the same mpg. Use a two sided test with unequal variances.  

1. Do you reject at the 5% level (enter 0 for no, 1 for yes).  
2. What is the P-value to 4 decimal places expressed as a proportion?  


## Question 3  
A sample of 100 men yielded an average PSA level of 3.0 with a sd of 1.1. What are the complete set of values that a 5% two sided Z test of $H_0:\mu=\mu_0$ would fail to reject the null hypothesis for?  

1. Enter the lower value to 2 decimal places.  
2. Enter the upper value to 2 decimal places.   


## Question 4  
You believe the coin that you're flipping is biased towards heads. You get 55 heads out of 100 flips.  

1. What's the exact relevant pvalue to 4 decimal places (expressed as a proportion)?  
2. Would you reject a 1 sided hypothesis at $\alpha=.05$? (0 for no 1 for yes)?  


## Question 5  
A web site was monitored for a year and it received 520 hits per day. In the first 30 days in the next year, the site received 15,800 hits. Assuming that web hits are Poisson.  

1. Give an exact one sided P-value to the hypothesis that web hits are up this year over last to four significant digits (expressed as a proportion).  
2. Does the one sided test reject (0 for no 1 for yes)?


## Question 6  
Suppose that in an AB test, one advertising scheme led to an average of 10 purchases per day for a sample of 100 days, while the other led to 11 purchaces per day, also for a sample of 100 days. Assuming a common standard deviation of 4 purchases per day. Assuming that the groups are independent and that they days are iid, perform a Z test of equivalence. 

1. What is the P-value reported to 3 digits expressed as a proportion?  
2. Do you reject the test? (0 for no 1 for yes).


## Question 7  
A confidence interval for the mean contains:  

* All of the values of the hypothesized mean for which we would fail to reject with $\alpha=1−Conf.Level$.
* All of the values of the hypothesized mean for which we would fail to reject with $2\alpha=1−Conf.Level$.
* All of the values of the hypothesized mean for which we would reject with $\alpha=1−Conf.Level$.
* All of the values of the hypothesized mean for which we would reject with $2\alpha=1−Conf.Level$.


## Question 8  
Consider two problems previous. Assuming that 10 purchases per day is a benchmark null value, that days are iid and that the standard deviation is 4 purchases for day. Suppose that you plan on sampling 100 days. What would be the power for a one sided 5% Z mean test that purchases per day have increased under the alternative of $\mu=11$ purchase per day?

1. Give your result as a proportion to 3 decimal places.

## Question 9  
Researchers would like to conduct a study of healthy adults to detect a four year mean brain volume loss of .01 mm3. Assume that the standard deviation of four year volume loss in this population is .04 mm3.  

1. What is necessary sample size for the study for a 5% one sided test versus a null hypothesis of no volume loss to achieve 80% power? (Always round up)


## Question 10  
In a court of law, all things being equal, if via policy you require a lower standard of evidence to convict people then  

* Less guilty people will be convicted.  
* More innocent people will be convicted.  
* More Innocent people will be not convicted.  


## Question 11  
Consider the mtcars data set.

1. Give the p-value for a t-test comparing MPG for 6 and 8 cylinder cars assuming equal variance, as a proportion to 3 decimal places.
2. Give the associated P-value for a z test.
3. Give the common standard deviation estimate for MPG across cylinders to 3 decimal places.
4. Would the t test reject at the two sided 0.05 level (0 for no 1 for yes)?


## Question 12  
The Bonferonni correction controls this

* False discovery rate
* The familywise error rate
* The rate of true rejections
* The number of true rejections

