---
title: "Regmods Quiz 4"
author: "Shawn Rich"
date: "January 30, 2016"
output: html_document
---
```{r echo=FALSE, results="hide", warning=FALSE, message=FALSE}
library(ggplot2)
library(UsingR)
library(datasets)
library(dplyr)
library(MASS)
data("galton")
data("father.son")
data("mtcars")
data("Seatbelts")
```

1. 

```{r}
#http://www.ats.ucla.edu/stat/r/dae/logit.htm
#http://www.r-bloggers.com/computing-odds-ratios-in-r/
data(shuttle)
shuttle$auto <- 1 * (shuttle$use == "auto")
shuttle$headwind <- 1 * (shuttle$wind == "head")

fit <- glm(auto ~ headwind, data = shuttle, family = binomial)
exp(coef(fit))
```


2. 

```{r}
data(shuttle)
head(shuttle)

df_shuttle <- as.data.frame(shuttle)
#nrow(df_shuttle)
#head(df_shuttle)
df_shuttle <- mutate(df_shuttle,
                     auto = 1 * (use == "auto"))
fit <- glm(auto ~ wind + magn, family = "binomial", data = df_shuttle)
round(summary(fit)$coef,4)
round(exp(summary(fit)$coef),4)
```

3.

```{r}
data(shuttle)

df_shuttle <- as.data.frame(shuttle)
df_shuttle <- mutate(df_shuttle,
                     auto = 1 * (use == "auto"))
fit1 <- glm(auto ~ wind, family = binomial, data = df_shuttle)
fit2 <- glm(I(1 - auto) ~ wind, family = binomial, data = df_shuttle)
summary(fit1)$coef
summary(fit2)$coef

```


4.

```{r}
data("InsectSprays")
head(InsectSprays)

fit <- glm(count ~ spray, family = "poisson", data = InsectSprays)

summary(fit)$coef
exp(summary(fit)$coef)
```


5. 

```{r}

```


6.

```{r}
x <- -5:5
y <- c(5.12, 3.93, 2.67, 1.87, 0.52, 0.08, 0.93, 2.05, 2.54, 3.87, 4.97)
z <- (x > 0) * x
fit <- lm(y ~ x + z)
sum(coef(fit)[2:3])
coef(fit)

plot(x,y)
x1 <- x[6]
y1 <- y[6]
x2 <- x[11]
y2 <- y[11]
c(x1,y1,x2,y2)
m = (y2 - y1)/(x2 - x1)
fit <- lm(y ~ x)
summary(fit)
```
